-- MySQL Script generated by MySQL Workbench
-- Sun May 21 18:30:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bigbread
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bigbread` ;

-- -----------------------------------------------------
-- Schema bigbread
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bigbread` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bigbread` ;

-- -----------------------------------------------------
-- Table `bigbread`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbread`.`ingredientes` (
  `id_ingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ingrediente`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bigbread`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbread`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bigbread`.`produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbread`.`produccion` (
  `id_produccion` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_produccion`),
  CONSTRAINT `produccion_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bigbread`.`productos` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_producto` ON `bigbread`.`produccion` (`id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bigbread`.`ingredientes_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbread`.`ingredientes_produccion` (
  `id_produccion` INT NULL DEFAULT NULL,
  `id_ingrediente` INT NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  CONSTRAINT `ingredientes_produccion_ibfk_1`
    FOREIGN KEY (`id_produccion`)
    REFERENCES `bigbread`.`produccion` (`id_produccion`),
  CONSTRAINT `ingredientes_produccion_ibfk_2`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `bigbread`.`ingredientes` (`id_ingrediente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_produccion` ON `bigbread`.`ingredientes_produccion` (`id_produccion` ASC) VISIBLE;

CREATE INDEX `id_ingrediente` ON `bigbread`.`ingredientes_produccion` (`id_ingrediente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
