-- MySQL Script generated by MySQL Workbench
-- Sat May 20 20:50:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `empresa` ;

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresa`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `id_departamento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`),
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `empresa`.`departamento` (`id_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_departamento` ON `empresa`.`empleado` (`id_departamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `empresa`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `empresa`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`asignacion` (
  `id_asignacion` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NULL DEFAULT NULL,
  `id_proyecto` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_asignacion`),
  CONSTRAINT `asignacion_ibfk_1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empresa`.`empleado` (`id_empleado`),
  CONSTRAINT `asignacion_ibfk_2`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `empresa`.`proyecto` (`id_proyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_empleado` ON `empresa`.`asignacion` (`id_empleado` ASC) VISIBLE;

CREATE INDEX `id_proyecto` ON `empresa`.`asignacion` (`id_proyecto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
